"""Initial backend database structure

Revision ID: 5a1bf3f79b73
Revises: 
Create Date: 2026-01-31 20:25:42.808571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a1bf3f79b73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_wheels_active'), table_name='wheels')
    op.drop_index(op.f('idx_wheels_symbol'), table_name='wheels')
    op.drop_table('wheels')
    op.drop_index(op.f('idx_trades_outcome'), table_name='trades')
    op.drop_index(op.f('idx_trades_symbol'), table_name='trades')
    op.drop_index(op.f('idx_trades_wheel'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('idx_snapshots_date'), table_name='position_snapshots')
    op.drop_index(op.f('idx_snapshots_trade'), table_name='position_snapshots')
    op.drop_table('position_snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_snapshots',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('trade_id', sa.INTEGER(), nullable=False),
    sa.Column('snapshot_date', sa.TEXT(), nullable=False),
    sa.Column('current_price', sa.REAL(), nullable=False),
    sa.Column('dte_calendar', sa.INTEGER(), nullable=False),
    sa.Column('dte_trading', sa.INTEGER(), nullable=False),
    sa.Column('moneyness_pct', sa.REAL(), nullable=False),
    sa.Column('is_itm', sa.INTEGER(), nullable=False),
    sa.Column('risk_level', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'snapshot_date')
    )
    op.create_index(op.f('idx_snapshots_trade'), 'position_snapshots', ['trade_id'], unique=False)
    op.create_index(op.f('idx_snapshots_date'), 'position_snapshots', ['snapshot_date'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('wheel_id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.TEXT(), nullable=False),
    sa.Column('direction', sa.TEXT(), nullable=False),
    sa.Column('strike', sa.REAL(), nullable=False),
    sa.Column('expiration_date', sa.TEXT(), nullable=False),
    sa.Column('premium_per_share', sa.REAL(), nullable=False),
    sa.Column('contracts', sa.INTEGER(), nullable=False),
    sa.Column('total_premium', sa.REAL(), nullable=False),
    sa.Column('opened_at', sa.TEXT(), nullable=False),
    sa.Column('closed_at', sa.TEXT(), nullable=True),
    sa.Column('outcome', sa.TEXT(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('price_at_expiry', sa.REAL(), nullable=True),
    sa.Column('close_price', sa.REAL(), nullable=True),
    sa.ForeignKeyConstraint(['wheel_id'], ['wheels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_trades_wheel'), 'trades', ['wheel_id'], unique=False)
    op.create_index(op.f('idx_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('idx_trades_outcome'), 'trades', ['outcome'], unique=False)
    op.create_table('wheels',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('symbol', sa.TEXT(), nullable=False),
    sa.Column('state', sa.TEXT(), server_default=sa.text("'cash'"), nullable=False),
    sa.Column('capital_allocated', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('shares_held', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_basis', sa.REAL(), nullable=True),
    sa.Column('profile', sa.TEXT(), server_default=sa.text("'conservative'"), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('idx_wheels_symbol'), 'wheels', ['symbol'], unique=False)
    op.create_index(op.f('idx_wheels_active'), 'wheels', ['is_active'], unique=False)
    # ### end Alembic commands ###
