"""Add portfolio support and enhance schema

Revision ID: 83821511f593
Revises: 
Create Date: 2026-02-01 03:44:23.263538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83821511f593'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema with portfolio support and data migration.

    This migration:
    1. Creates new tables (portfolios, scheduler_config, performance_metrics, snapshots)
    2. Creates a default portfolio
    3. Migrates existing wheels to default portfolio
    4. Migrates position_snapshots to snapshots with wheel_id
    5. Enhances existing tables with new columns and relationships
    """
    from datetime import datetime
    import uuid

    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create portfolios table
    op.create_table('portfolios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_capital', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduler_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_type', sa.String(), nullable=False),
    sa.Column('schedule_params', sa.Text(), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'task_name', name='uq_portfolio_task')
    )
    op.create_index(op.f('ix_scheduler_config_portfolio_id'), 'scheduler_config', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_scheduler_config_task_name'), 'scheduler_config', ['task_name'], unique=False)
    op.create_table('performance_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=True),
    sa.Column('wheel_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_premium', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('annualized_return', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wheel_id'], ['wheels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_metrics_period_end'), 'performance_metrics', ['period_end'], unique=False)
    op.create_index(op.f('ix_performance_metrics_period_start'), 'performance_metrics', ['period_start'], unique=False)
    op.create_index(op.f('ix_performance_metrics_portfolio_id'), 'performance_metrics', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_performance_metrics_wheel_id'), 'performance_metrics', ['wheel_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('wheel_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.String(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('dte_calendar', sa.Integer(), nullable=False),
    sa.Column('dte_trading', sa.Integer(), nullable=False),
    sa.Column('moneyness_pct', sa.Float(), nullable=False),
    sa.Column('is_itm', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wheel_id'], ['wheels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'snapshot_date', name='uq_trade_snapshot_date')
    )
    op.create_index(op.f('ix_snapshots_snapshot_date'), 'snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_snapshots_trade_id'), 'snapshots', ['trade_id'], unique=False)
    op.create_index(op.f('ix_snapshots_wheel_id'), 'snapshots', ['wheel_id'], unique=False)

    # Step 2: Create default portfolio (before modifying wheels table)
    # This must happen before we add the portfolio_id column to wheels
    default_portfolio_id = str(uuid.uuid4())
    now = datetime.utcnow().isoformat()

    conn = op.get_bind()
    conn.execute(
        sa.text(
            "INSERT INTO portfolios (id, name, description, default_capital, created_at, updated_at) "
            "VALUES (:id, :name, :description, :capital, :created, :updated)"
        ),
        {
            "id": default_portfolio_id,
            "name": "Default Portfolio",
            "description": "Auto-created portfolio for existing wheels",
            "capital": None,
            "created": now,
            "updated": now
        }
    )

    # Step 3: Migrate position_snapshots to snapshots table
    # First, copy data with wheel_id from associated trades
    conn.execute(
        sa.text("""
            INSERT INTO snapshots
            (trade_id, wheel_id, snapshot_date, current_price, dte_calendar,
             dte_trading, moneyness_pct, is_itm, risk_level, created_at)
            SELECT
                ps.trade_id,
                t.wheel_id,
                ps.snapshot_date,
                ps.current_price,
                ps.dte_calendar,
                ps.dte_trading,
                ps.moneyness_pct,
                ps.is_itm,
                ps.risk_level,
                ps.created_at
            FROM position_snapshots ps
            JOIN trades t ON t.id = ps.trade_id
        """)
    )

    # Now drop the old table
    op.drop_index(op.f('idx_snapshots_date'), table_name='position_snapshots')
    op.drop_index(op.f('idx_snapshots_trade'), table_name='position_snapshots')
    op.drop_table('position_snapshots')
    op.alter_column('trades', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('trades', 'symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('trades', 'direction',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('trades', 'strike',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('trades', 'expiration_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('trades', 'premium_per_share',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('trades', 'total_premium',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('trades', 'opened_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('trades', 'closed_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('trades', 'outcome',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'open'"))
    op.alter_column('trades', 'price_at_expiry',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('trades', 'close_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('idx_trades_outcome'), table_name='trades')
    op.drop_index(op.f('idx_trades_symbol'), table_name='trades')
    op.drop_index(op.f('idx_trades_wheel'), table_name='trades')
    op.create_index(op.f('ix_trades_expiration_date'), 'trades', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_trades_outcome'), 'trades', ['outcome'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_trades_wheel_id'), 'trades', ['wheel_id'], unique=False)
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_foreign_key(None, 'trades', 'wheels', ['wheel_id'], ['id'], ondelete='CASCADE')

    # Step 4: Add portfolio_id column to wheels (nullable initially)
    op.add_column('wheels', sa.Column('portfolio_id', sa.String(), nullable=True))

    # Step 5: Update all existing wheels to use default portfolio
    conn.execute(
        sa.text("UPDATE wheels SET portfolio_id = :portfolio_id"),
        {"portfolio_id": default_portfolio_id}
    )

    # Step 6: Make portfolio_id NOT NULL now that data is migrated
    op.alter_column('wheels', 'portfolio_id', nullable=False)
    op.alter_column('wheels', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('wheels', 'symbol',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('wheels', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'cash'"))
    op.alter_column('wheels', 'capital_allocated',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('wheels', 'cost_basis',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('wheels', 'profile',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'conservative'"))
    op.alter_column('wheels', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('wheels', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('wheels', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_wheels_is_active'), 'wheels', ['is_active'], unique=False)
    op.create_index(op.f('ix_wheels_portfolio_id'), 'wheels', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_wheels_symbol'), 'wheels', ['symbol'], unique=False)
    op.create_unique_constraint('uq_portfolio_symbol', 'wheels', ['portfolio_id', 'symbol'])
    op.create_foreign_key(None, 'wheels', 'portfolios', ['portfolio_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wheels', type_='foreignkey')
    op.drop_constraint('uq_portfolio_symbol', 'wheels', type_='unique')
    op.drop_index(op.f('ix_wheels_symbol'), table_name='wheels')
    op.drop_index(op.f('ix_wheels_portfolio_id'), table_name='wheels')
    op.drop_index(op.f('ix_wheels_is_active'), table_name='wheels')
    op.alter_column('wheels', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('wheels', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('wheels', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('wheels', 'profile',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'conservative'"))
    op.alter_column('wheels', 'cost_basis',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('wheels', 'capital_allocated',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('wheels', 'state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'cash'"))
    op.alter_column('wheels', 'symbol',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('wheels', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('wheels', 'portfolio_id')
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_foreign_key(None, 'trades', 'wheels', ['wheel_id'], ['id'])
    op.drop_index(op.f('ix_trades_wheel_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_outcome'), table_name='trades')
    op.drop_index(op.f('ix_trades_expiration_date'), table_name='trades')
    op.create_index(op.f('idx_trades_wheel'), 'trades', ['wheel_id'], unique=False)
    op.create_index(op.f('idx_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_index(op.f('idx_trades_outcome'), 'trades', ['outcome'], unique=False)
    op.alter_column('trades', 'close_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('trades', 'price_at_expiry',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('trades', 'outcome',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'open'"))
    op.alter_column('trades', 'closed_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('trades', 'opened_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('trades', 'total_premium',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trades', 'premium_per_share',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trades', 'expiration_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('trades', 'strike',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('trades', 'direction',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('trades', 'symbol',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('trades', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('position_snapshots',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('trade_id', sa.INTEGER(), nullable=False),
    sa.Column('snapshot_date', sa.TEXT(), nullable=False),
    sa.Column('current_price', sa.REAL(), nullable=False),
    sa.Column('dte_calendar', sa.INTEGER(), nullable=False),
    sa.Column('dte_trading', sa.INTEGER(), nullable=False),
    sa.Column('moneyness_pct', sa.REAL(), nullable=False),
    sa.Column('is_itm', sa.INTEGER(), nullable=False),
    sa.Column('risk_level', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'snapshot_date')
    )
    op.create_index(op.f('idx_snapshots_trade'), 'position_snapshots', ['trade_id'], unique=False)
    op.create_index(op.f('idx_snapshots_date'), 'position_snapshots', ['snapshot_date'], unique=False)
    op.drop_index(op.f('ix_snapshots_wheel_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_trade_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_snapshot_date'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_performance_metrics_wheel_id'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_portfolio_id'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_period_start'), table_name='performance_metrics')
    op.drop_index(op.f('ix_performance_metrics_period_end'), table_name='performance_metrics')
    op.drop_table('performance_metrics')
    op.drop_index(op.f('ix_scheduler_config_task_name'), table_name='scheduler_config')
    op.drop_index(op.f('ix_scheduler_config_portfolio_id'), table_name='scheduler_config')
    op.drop_table('scheduler_config')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
